---
  sensative_path: "/Users/huan/desktop/OcrSentence/app/datasets/words.txt"
  word_vector_path: "/Users/huan/desktop/OcrSentence/app/datasets/Tencent_AILab_ChineseEmbedding/Tencent_AILab_ChineseEmbedding.txt"
  
  
  
  
  